name: CI/CD Pipeline - Book Reservation Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug environment
        run: |
          echo "PYTHONPATH: $PYTHONPATH"
          ls -l
          pip list

      - name: Run linter (Pylint)
        run: |
          pylint app.py

      - name: Run tests
        run: |
          pytest

  deploy:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Notify Deployment Started
        run: echo "All tests passed. Starting deployment..."

      - name: Deploy to Render (Example)
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          response=$(curl -s -o response.json -w "%{http_code}" -m 30 \
            -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys)

          cat response.json

          if [ "$response" != "201" ]; then
            echo "Deployment failed with status $response"
            exit 1
          fi

          
